name: "NF Pipeline"
on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup NextFlow
        uses: nf-core/setup-nextflow@v1.2.0
      
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      
      - name: Execute NF Pipeline
        run: |
          set -x
          docker pull djmolitor/nextflow-example:latest
          nextflow run main.nf
          mkdir _site
          cp -R source/analysis-report.html source/analysis-report_files _site
          echo "" >> _site/.nojekyll
      
      - name: Install rsync
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
